-- Generated by the database client.
CREATE TABLE departements(
    id SERIAL NOT NULL,
    nom varchar(100) NOT NULL,
    PRIMARY KEY(id)
);



CREATE TABLE modules(
    id SERIAL NOT NULL,
    nom varchar(100) NOT NULL,
    formation_id integer,
    nb_heures integer NOT NULL,
    departement_id integer,
    niveau varchar(10),
    PRIMARY KEY(id),
    CONSTRAINT fk_module_dept FOREIGN key(departement_id) REFERENCES departements(id)
);




CREATE TABLE salles(
    id SERIAL NOT NULL,
    nom varchar(50) NOT NULL,
    capacite integer NOT NULL,
    departement_id integer,
    PRIMARY KEY(id),
    CONSTRAINT fk_salle_dept FOREIGN key(departement_id) REFERENCES departements(id)
);



CREATE TABLE professeurs(
    id SERIAL NOT NULL,
    nom varchar(100) NOT NULL,
    prenom varchar(100) NOT NULL,
    departement_id integer,
    PRIMARY KEY(id),
    CONSTRAINT professeurs_departement_id_fkey FOREIGN key(departement_id) REFERENCES departements(id)
);





CREATE TABLE etudiants(
    id SERIAL NOT NULL,
    nom varchar(100) NOT NULL,
    prenom varchar(100) NOT NULL,
    departement_id integer,
    niveau varchar(2),
    PRIMARY KEY(id),
    CONSTRAINT etudiants_departement_id_fkey FOREIGN key(departement_id) REFERENCES departements(id)
);







CREATE TABLE examens(
    id SERIAL NOT NULL,
    module_id integer,
    salle_id integer,  -- AJOUTEZ CETTE LIGNE
    date_exam date NOT NULL,
    heure_debut time without time zone NOT NULL,
    duree integer NOT NULL,
    niveau varchar(10),
    PRIMARY KEY(id),
    CONSTRAINT examens_module_id_fkey FOREIGN KEY (module_id) REFERENCES modules(id),
    CONSTRAINT fk_examens_salle FOREIGN KEY (salle_id) REFERENCES salles(id)  -- AJOUTEZ
);






	


CREATE TABLE exam_conflicts(
    id SERIAL NOT NULL,
    exam_id integer,
    conflict_type varchar(50),
    conflict_detail text,
    resolved boolean DEFAULT false,
    PRIMARY KEY(id),
    CONSTRAINT exam_conflicts_exam_id_fkey FOREIGN key(exam_id) REFERENCES examens(id)
);



CREATE TABLE exam_salle_affectation(
    id SERIAL NOT NULL,
    exam_id integer,
    salle_id integer,
    PRIMARY KEY(id),
    CONSTRAINT exam_salle_affectation_exam_id_fkey FOREIGN key(exam_id) REFERENCES examens(id),
    CONSTRAINT exam_salle_affectation_salle_id_fkey FOREIGN key(salle_id) REFERENCES salles(id)
);




CREATE TABLE exam_room_students(
    id SERIAL NOT NULL,
    exam_id integer,
    salle_id integer,
    etudiant_id integer,
    PRIMARY KEY(id),
    CONSTRAINT exam_room_students_exam_id_fkey FOREIGN key(exam_id) REFERENCES examens(id),
    CONSTRAINT exam_room_students_salle_id_fkey FOREIGN key(salle_id) REFERENCES salles(id),
    CONSTRAINT exam_room_students_etudiant_id_fkey FOREIGN key(etudiant_id) REFERENCES etudiants(id)
);
CREATE UNIQUE INDEX exam_room_students_exam_id_etudiant_id_key ON public.exam_room_students USING btree (exam_id, etudiant_id);



-- Generated by the database client.
CREATE TABLE inscriptions(
    id SERIAL NOT NULL,
    etudiant_id integer,
    examen_id integer,
    module_id integer NOT NULL,
    PRIMARY KEY(id),
    CONSTRAINT inscriptions_etudiant_id_fkey FOREIGN key(etudiant_id) REFERENCES etudiants(id),
    CONSTRAINT inscriptions_examen_id_fkey FOREIGN key(examen_id) REFERENCES examens(id),
    CONSTRAINT fk_inscriptions_module FOREIGN key(module_id) REFERENCES modules(id)
);
CREATE UNIQUE INDEX inscriptions_etudiant_id_examen_id_key ON public.inscriptions USING btree (etudiant_id, examen_id);
CREATE INDEX idx_inscriptions_etudiant_date ON public.inscriptions USING btree (examen_id, etudiant_id) WHERE (examen_id IS NOT NULL);







CREATE TABLE surveillances(
    id SERIAL NOT NULL,
    professeur_id integer,
    examen_id integer,
    PRIMARY KEY(id),
    CONSTRAINT surveillances_professeur_id_fkey FOREIGN key(professeur_id) REFERENCES professeurs(id),
    CONSTRAINT surveillances_examen_id_fkey FOREIGN key(examen_id) REFERENCES examens(id)
);
CREATE UNIQUE INDEX surveillances_professeur_id_examen_id_key ON public.surveillances USING btree (professeur_id, examen_id);
CREATE INDEX idx_surveillances_prof_date ON public.surveillances USING btree (examen_id, professeur_id) WHERE (examen_id IS NOT NULL);
